//
//  Theme.m
//  Practice
//
//  Created by Ibrahim on 20/05/2016.
//  Copyright © 2016 Ibrahim. All rights reserved.
//


// IMPORT

#import "Font Size.h"


// IMPLEMENTATION

    // GENERAL

    CGFloat const FONT_SIZE_GENERAL = 16;


    // FORM

    CGFloat const FONTSIZE_FORM_TITLE = FONT_SIZE_GENERAL + 2;
    CGFloat const FONTSIZE_FORM_FIELD = FONT_SIZE_GENERAL;
    CGFloat const FONTSIZE_FORM_TEXTFIELD = FONT_SIZE_GENERAL;

    // NOTE

    CGFloat const FONTSIZE_NOTE_HEADER = FONT_SIZE_GENERAL;
    CGFloat const FONTSIZE_NOTE_DETAIL = FONT_SIZE_GENERAL;

    // GUIDE

    CGFloat const FONTSIZE_GUIDEMENU_STEP = FONT_SIZE_GENERAL * 2;
    CGFloat const FONTSIZE_GUIDEMENU_HEADER = FONT_SIZE_GENERAL + 2;
    CGFloat const FONTSIZE_GUIDEMENU_DETAIL = FONT_SIZE_GENERAL - 4;
    CGFloat const FONTSIZE_GUIDEFORM_STEP = FONT_SIZE_GENERAL * 1.8;
    CGFloat const FONTSIZE_GUIDEFORM_HEADER = FONT_SIZE_GENERAL + 2;

    // INFORMATION

    CGFloat const FONTSIZE_INFORMATION_HEADER = FONT_SIZE_GENERAL - 2;
    CGFloat const FONTSIZE_INFORMATION_DETAIL = FONT_SIZE_GENERAL - 4;

    // TABLE

    CGFloat const FONTSIZE_TABLE_HEADER = FONT_SIZE_GENERAL - 2;
    CGFloat const FONTSIZE_TABLE_DETAIL = FONT_SIZE_GENERAL - 4;

    // BUTTON

    CGFloat const FONTSIZE_FORM_BUTTON = FONT_SIZE_GENERAL;
    CGFloat const FONTSIZE_NAVIGATION_BUTTON = FONT_SIZE_GENERAL - 5;